const Page = require("../../utils/localized-page");
const { planCard, drawCard } = require("../../utils/share-card");

function call(name, options) {
  return new Promise((resolve, reject) => wx[name]({ ...options, success: resolve, fail: reject }));
}

Page({
  data: { layout: "separate", hasPhoto: false, imageUrls: [], backgroundIndex: 0, busy: true, saving: false, cards: [], selected: 0, error: "" },
  onLoad() {
    // Receive one explicitly selected entry in memory; never put private data in a URL/storage.
    wx.hideShareMenu();
    this.files = new Set();
    this.getOpenerEventChannel().on("entry", ({ entry, locale }) => {
      clearTimeout(this.entryTimer);
      this.entry = entry;
      this.locale = locale || "zh";
      const imageUrls = entry.entry_media?.length ? entry.entry_media.map((item) => item.signed_url || "") : entry.imageUrls || (entry.imageUrl ? [entry.imageUrl] : []);
      this.setData({ hasPhoto: imageUrls.length > 0, imageUrls });
      if (this.ready) this.generate();
    });
  },
  onReady() {
    this.ready = true;
    if (this.entry) this.generate();
    else this.entryTimer = setTimeout(() => {
      if (!this.entry && !this.closed) this.setData({ busy: false, error: "请从自己的记录中选择“分享”，再预览这一天。" });
    }, 3000);
  },
  onUnload() {
    this.closed = true;
    clearTimeout(this.entryTimer);
    // Only remove temporary images generated by this page, never user photo files.
    this.files.forEach((filePath) => wx.getFileSystemManager().unlink({ filePath, fail() {} }));
    this.entry = null;
    this.photos = null;
  },
  chooseLayout(event) {
    const layout = event.currentTarget.dataset.layout;
    if (this.data.busy || !["separate", "overlay"].includes(layout) || (layout === "overlay" && !this.data.hasPhoto)) return;
    this.setData({ layout });
    this.generate();
  },
  selectCard(event) { this.setData({ selected: Number(event.currentTarget.dataset.index) }); },
  chooseBackground(event) {
    if (this.data.busy) return;
    this.setData({ backgroundIndex: Number(event.currentTarget.dataset.index) });
    this.generate();
  },
  async generate() {
    if (!this.entry || this.generating || this.closed) return;
    this.generating = true;
    this.data.cards.forEach((card) => { wx.getFileSystemManager().unlink({ filePath: card.path, fail() {} }); this.files.delete(card.path); });
    this.setData({ busy: true, error: "", cards: [], selected: 0 });
    try {
      const canvas = this.canvas || await new Promise((resolve, reject) => {
        wx.createSelectorQuery().in(this).select("#shareCanvas").fields({ node: true, size: true }).exec((rows) => {
          if (rows?.[0]?.node) resolve(rows[0].node);
          else reject(new Error("图片组件尚未准备好，请重试。"));
        });
      });
      this.canvas = canvas;
      if (!this.photos) {
        const photos = [];
        for (const url of this.data.imageUrls) {
        if (!url) throw new Error("有照片无法读取，请刷新记录后重试；不会省略照片。" );
        const info = await call("getImageInfo", { src: url });
        let path = /^(?:https?:|wxfile:|file:|\/)/.test(info.path) ? info.path : `/${info.path}`;
        if (Math.max(info.width, info.height) > 1200) {
          const ratio = 1200 / Math.max(info.width, info.height);
          try {
            const reduced = await call("compressImage", { src: path, quality: 88, compressedWidth: Math.round(info.width * ratio), compressedHeight: Math.round(info.height * ratio) });
            path = reduced.tempFilePath;
            if (this.closed) { wx.getFileSystemManager().unlink({ filePath: path, fail() {} }); return; }
            this.files.add(path);
          } catch { /* Native decoder can still render a supported original. */ }
        }
        photos.push(await new Promise((resolve, reject) => {
          const photo = canvas.createImage();
          photo.onload = () => resolve(photo);
          photo.onerror = () => reject(new Error("照片加载失败，请返回记录列表刷新后重试。"));
          // Bundled images can be returned without a leading slash. Canvas resolves
          // those against this page, unlike wx.getImageInfo.
          photo.src = path;
        }));
        }
        if (this.closed) return;
        this.photos = photos;
      }
      const content = this.entry.content || (this.locale === "en" ? "Today was worth remembering." : "今天，也值得被记住。");
      const plan = planCard(canvas.getContext("2d"), content, this.photos, this.data.layout, { backgroundIndex: this.data.backgroundIndex });
      const cards = [];
      for (let i = 0; i < plan.pages.length; i++) {
        if (this.closed) return;
        drawCard(canvas, this.photos, this.entry, plan, i, this.locale);
        const result = await call("canvasToTempFilePath", {
          canvas, x: 0, y: 0, width: plan.width, height: plan.pages[i].height,
          destWidth: plan.width, destHeight: plan.pages[i].height, fileType: "png",
        });
        if (this.closed) { wx.getFileSystemManager().unlink({ filePath: result.tempFilePath, fail() {} }); return; }
        this.files.add(result.tempFilePath);
        cards.push({ path: result.tempFilePath });
      }
      if (!this.closed) this.setData({ cards });
    } catch (error) {
      if (!this.closed) this.setData({ error: error.message || "分享卡生成失败，请返回刷新记录后重试。" });
    } finally {
      this.generating = false;
      if (!this.closed) this.setData({ busy: false });
    }
  },
  async shareImage() {
    const card = this.data.cards[this.data.selected];
    if (!card || this.data.busy) return;
    if (typeof wx.showShareImageMenu !== "function") {
      wx.previewImage({ urls: this.data.cards.map((item) => item.path), current: card.path });
      return;
    }
    try {
      await call("showShareImageMenu", { path: card.path, needShowEntrance: true, entrancePath: "pages/index/index" });
    } catch (error) {
      if (/cancel/i.test(error.errMsg || "")) return;
      wx.showModal({ title: "也可以长按图片分享", content: "如果当前微信版本没有朋友圈选项，请保存图片后在朋友圈发布，或更新微信。", showCancel: false });
    }
  },
  async saveImage() {
    const card = this.data.cards[this.data.selected];
    if (!card || this.data.saving) return;
    this.setData({ saving: true });
    try {
      await call("saveImageToPhotosAlbum", { filePath: card.path });
      wx.showToast({ title: "已保存到相册", icon: "success" });
    } catch (error) {
      if (/auth|deny|denied/i.test(error.errMsg || "")) {
        wx.showModal({ title: "需要相册权限", content: "允许后即可保存分享卡。", confirmText: "去设置", success: (result) => { if (result.confirm) wx.openSetting({}); } });
      } else if (!/cancel/i.test(error.errMsg || "")) wx.showToast({ title: "保存失败，请重试", icon: "none" });
    } finally { if (!this.closed) this.setData({ saving: false }); }
  },
});
